.\"                                      Hey, EMACS: -*- nroff -*-
.TH defoma-id 1 "March  4, 2001"
.SH NAME
defoma-id \- Manage id\-cache of Debian Font Manager
.SH SYNOPSIS
.B defoma-id
.RI [ options ]
.B list-cache
.I app
.br
.B defoma-id
.RI [ options ] 
.B install
.I app/id-cache id font
.br
.B defoma-id
.RI [ options ] 
.B exclude
.I app/id-cache id font
.br
.B defoma-id
.RI [ options ]
.B unset
.I app/id-cache id font
.br
.B defoma-id
.RI [ options ]
.B add-alias
.I app/id-cache id font alias
.br
.B defoma-id
.RI [ options ]
.B remove-alias
.I app/id-cache alias font
.SH DESCRIPTION
.B defoma-id
is supposed to be invoked not from a command line, but from dfontmgr.
.SH SEE ALSO
.BR defoma (1).
.BR dfontmgr (1).

