.\"                                      Hey, EMACS: -*- nroff -*-
.TH defoma-user 1 "June  15, 2003"
.SH NAME
defoma-user \- Debian Font Manager for users
.SH SYNOPSIS
.B defoma-user
.RI [ options ]
.B reconfigure
.br
.B defoma-user
.RI [ options ] 
.B update
.br
.B defoma-user
.RI [ options ] 
.B update-font
.SH DESCRIPTION
I have no idea what
.B defoma-user
does just yet.  I'm working on it..
.SH SEE ALSO
.BR defoma (1).
.BR dfontmgr (1).
