.\"Traduction Jeudi 8 novembre 2002 par Antoine Gémis
.\"(agemis@netuup.com)
.\"(defoma 0.11.1) 
.\"                                      Hey, EMACS: -*- nroff -*-
.TH defoma-id 1 "4 mars 2001"
.SH NOM
defoma-id \- gère la base de référence du gestionnaire de polices Debian.
.SH SYNOPSIS
.B defoma-id
.RI [ options ]
.B list-cache
.I application
.br
.B defoma-id
.RI [ options ] 
.B install
.I application/base-de-référence identifiant police
.br
.B defoma-id
.RI [ options ] 
.B exclude
.I application/base-de-référence identifiant police
.br
.B defoma-id
.RI [ options ]
.B unset
.I application/base-de-référence identifiant police
.br
.B defoma-id
.RI [ options ]
.B add-alias
.I application/base-de-référence identifiant police alias
.br
.B defoma-id
.RI [ options ]
.B remove-alias
.I application/base-de-référence alias police
.SH DESCRIPTION
.B defoma-id
est conçu pour être appelé par dfontmgr et non en ligne de commande.
.SH VOIR AUSSI
.BR defoma (1).
.BR dfontmgr (1).
.SH TRADUCTION
Antoine Gémis <agemis@netuup.com>.
