#!/usr/bin/perl -w
#
# This is an example of a subclass of the generated application
#
# You can safely edit this file, any changes that you make will be preserved
# and this file will not be overwritten by the next run of Glade::PerlGenerate
#
#==============================================================================
#=== This is the 'Subwindow1' class                              
#==============================================================================
package Subwindow1;
require 5.000; use strict 'vars', 'refs', 'subs';
# UI class 'Subwindow1' (version 0.01)
# 
# Copyright (c) Date 2001年 11月 16日 金曜日 22:44:05 JST
# Author Yasuhiro Take,,, <redstar\@laminar>
#
## Unspecified copying policy, please contact the author\n#  Yasuhiro Take,,, <redstar\@laminar>
#
#==============================================================================
# This perl source file was automatically generated by 
# Glade::PerlGenerate version 0.59 - Wed Jun 20 14:48:25 BST 2001
# Copyright (c) Author Dermot Musgrove <dermot.musgrove\@virgin.net>
#
# from Glade file /home/redstar/Projects/defomawizard/defomawizard.glade
# 2001年 11月 16日 金曜日 22:44:05 JST
#==============================================================================

BEGIN {
    use vars qw( 
                 @ISA
                 %fields
                 $PACKAGE
                 $VERSION
                 $AUTHOR
                 $DATE
                 $permitted_fields
             );
    # Existing signal handler modules
    use src::DefomaWizard;
    # Uncomment the line below to enable gettext checking
#    use Glade::PerlSource;
    # Tell interpreter who we are inheriting from
    @ISA     = qw( window1 );
    # Uncomment the line below to enable gettext checking
#    @ISA      = qw( window1 Glade::PerlSource );
    $PACKAGE = 'SubDefomaWizard';
    $VERSION = '0.01';
    $AUTHOR  = 'Yasuhiro Take,,, <redstar\@laminar>';
    $DATE    = '2001年 11月 16日 金曜日 22:44:05 JST';
    $permitted_fields = '_permitted_fields';             
    # Inherit the AUTOLOAD dynamic methods from window1
    *AUTOLOAD = \&window1::AUTOLOAD;
} # End of sub BEGIN

%fields = (
# Insert any extra data access methods that you want to add to 
#   our inherited super-constructor (or overload)
    USERDATA    => undef,
    VERSION     => '0.01',
);

sub DESTROY {
    # This sub will be called on object destruction
} # End of sub DESTROY

#==============================================================================
#=== Below are the overloaded class constructors
#==============================================================================
sub new {
    my $that  = shift;
    # Allow indirect constructor so that we can call eg. 
    #   $window1 = BusFrame->new; $window2 = $window1->new;
    my $class = ref($that) || $that;

    # Call our super-class constructor to get an object and reconsecrate it
    my $self = bless $that->SUPER::new(), $class;

    # Add our own data access methods to the inherited constructor
    my($element);
    foreach $element (keys %fields) {
        $self->{$permitted_fields}->{$element} = $fields{$element};
    }
    @{$self}{keys %fields} = values %fields;
    return $self;
} # End of sub new

sub app_run {
    my ($class) = @_;
    Gtk->init;
    # Uncomment the line below to enable gettext checking
#    $class->check_gettext_strings;
    my $window = $class->new;
    # Insert your subclass user data key/value pairs 
    $window->USERDATA({
#        'Key1'   => 'Value1',
#        'Key2'   => 'Value2',
#        'Key3'   => 'Value3',
    });
    $window->TOPLEVEL->show;
#    my $window2 = $window->new;
#    $window2->TOPLEVEL->show;
    Gtk->main;
    # Uncomment the line below to enable gettext checking
#    $window->write_gettext_strings("__", '/home/redstar/Projects/defomawizard/src/DefomaWizard.pot');
    $window->TOPLEVEL->destroy;

    return $window;
} # End of sub run
#===============================================================================
#=== Below are (overloaded) default signal handlers for 'window1' class 
#===============================================================================
sub about_Form {
    my ($class) = @_;
    my $gtkversion = 
        Gtk->major_version.".".
        Gtk->minor_version.".".
        Gtk->micro_version;
    my $name = $0;
    my $message = 
        __PACKAGE__." ("._("version")." $VERSION - $DATE)\n".
        _("Written by")." $AUTHOR \n\n".
        _("No description")." \n\n".
        "Gtk ".     _("version").": $gtkversion\n".
        "Gtk-Perl "._("version").": $Gtk::VERSION\n".
        _("run from file").": $name";
    __PACKAGE__->message_box($message, _("About")." \u".__PACKAGE__, [_('Dismiss'), _('Quit Program')], 1,
        "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm", 'left' );
} # End of sub about_Form

sub destroy_Form {
    my ($class, $data, $object, $instance) = @_;
    Gtk->main_quit; 
} # End of sub destroy_Form

sub toplevel_hide    { shift->get_toplevel->hide    }
sub toplevel_close   { shift->get_toplevel->close   }
sub toplevel_destroy { shift->get_toplevel->destroy }

#==============================================================================
#=== Below are (overloaded) signal handlers for 'window1' class 
#==============================================================================
sub on_cancel_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_cancel_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_cancel_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_cancel_clicked(@_);

} # End of sub on_cancel_clicked

sub on_clist_select_row {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_clist_select_row";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_clist_select_row." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_clist_select_row(@_);

} # End of sub on_clist_select_row

sub on_clist_unselect_row {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_clist_unselect_row";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_clist_unselect_row." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_clist_unselect_row(@_);

} # End of sub on_clist_unselect_row

sub on_entry_activate {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_entry_activate";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_entry_activate." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_entry_activate(@_);

} # End of sub on_entry_activate

sub on_ok_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_ok_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_ok_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_ok_clicked(@_);

} # End of sub on_ok_clicked

sub on_radiobutton_no_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_radiobutton_no_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_radiobutton_no_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_radiobutton_no_clicked(@_);

} # End of sub on_radiobutton_no_clicked

sub on_radiobutton_yes_clicked {
    my ($class, $data, $object, $instance, $event) = @_;
    my $me = __PACKAGE__."->on_radiobutton_yes_clicked";
    # Get ref to hash of all widgets on our form
    my $form = $__PACKAGE__::all_forms->{$instance};

    # REPLACE the lines below with the actions to be taken when __PACKAGE__."->on_radiobutton_yes_clicked." is called
#    __PACKAGE__->show_skeleton_message($me, \@_, __PACKAGE__, "$Glade::PerlRun::pixmaps_directory/glade2perl_logo.xpm");
    shift->SUPER::on_radiobutton_yes_clicked(@_);

} # End of sub on_radiobutton_yes_clicked











1;

__END__

#===============================================================================
#==== Documentation
#===============================================================================
=pod

=head1 NAME

SubDefomaWizard - version 0.01 2001年 11月 16日 金曜日 22:44:05 JST

No description

=head1 SYNOPSIS

 use SubDefomaWizard;

 To construct the window object and show it call
 
 Gtk->init;
 my $window = Subwindow1->new;
 $window->TOPLEVEL->show;
 Gtk->main;
 
 OR use the shorthand for the above calls
 
 Subwindow1->app_run;

=head1 DESCRIPTION

Unfortunately, the author has not yet written any documentation :-(

=head1 AUTHOR

Yasuhiro Take,,, <redstar\@laminar>

=cut
